window.serverSettingsJSON = {
    "general" : {
        "maxBytesUnknownType": "4000",
        "dataDir": "/data",
        "textContentTypes": [
        "text/cmd",
        "text/css",
        "text/csv",
        "text/example",
        "text/html",
        "text/javascript",
        "text/plain",
        "text/rtf",
        "text/vcard",
        "text/vnd.abc",
        "text/xml",
        "text/x-jquery-tmpl",
        "application/x-javascript:",
        "application/x-latex",
        "text/x-markdown",
        "application/x-www-form-urlencoded",
        "multipart/mixed",
        "multipart/alternative",
        "multipart/related",
        "multipart/form-data",
        "multipart/signed",
        "multipart/encrypted",
        "multipart/example",
        "application/json",
        "application/javascript",
        "application/atom+xml",
        "application/dart",
        "application/ecmascript",
        "application/xhtml+xml",
        "application/xml",
        "application/postscript",
        "application/rss+xml",
        "application/soap+xml",
        "application/xml-dtd"
        ],
        "binContentTypes": [
        "image/gif",
        "image/jpeg",
        "image/pjpeg",
        "image/png",
        "image/webp",
        "image/vnd.djvu",
        "audio/basic",
        "audio/L24",
        "audio/mp4",
        "audio/mpeg",
        "audio/ogg",
        "audio/opus",
        "audio/vorbis",
        "audio/vnd.rn-realaudio",
        "audio/vnd.wave",
        "audio/webm",
        "audio/example",
        "video/avi",
        "video/example",
        "video/mpeg",
        "video/mp4",
        "video/ogg",
        "video/quicktime",
        "video/webm",
        "video/x-matroska",
        "video/x-ms-wmv",
        "video/x-flv",
        "application/x-7z-compressed",
        "application/x-chrome-extension",
        "application/x-dvi",
        "application/x-font-ttf",
        "application/x-mpegURL",
        "application/x-rar-compressed",
        "application/x-shockwave-flash",
        "application/x-stuffit",
        "application/x-tar",
        "application/x-xpinstall",
        "audio/x-aac",
        "audio/x-caf",
        "image/x-xcf",
        "text/x-gwt-rpc",
        "application/x-pkcs12",
        "application/EDI-X12",
        "application/EDIFACT",
        "application/octet-stream",
        "application/ogg",
        "application/pdf",
        "application/rdf+xml",
        "application/font-woff",
        "application/xop+xml",
        "application/zip",
        "application/gzip",
        "application/example",
        "application/x-nacl",
        "application/x-pnacl"
        ]
    },
    "API": {
       "host": "127.0.0.1",
       "port": "9080"
    },
    "IDE": {
       "host": "127.0.0.1",
       "port": "9085"
    },
    "DB": {
        "host": "127.0.0.1",
        "port": "8085",
        "type": "local"
    },
    "GUI": {
        "host": "127.0.0.1",
        "port": "3000"
    },
    "user": {
        "username": "ZeroCool",
        "authToken": "asdf",
        "session": {
            "project" : "proxyHistory",
            "selectedItem": "35",
            "profile" : "Logger"
        }
    },
    "id": "1",
    "firstRun": "true",
}
